service: aws-node-typescript
frameworkVersion: '3'

useDotenv: true

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: prod
  apiGateway:
    apiKeys:
      - name: ${sls:stage}_API_KEY
        value: ${env:API_GATEWAY_KEY, 'GX83SFHVFISZDNE4N32L'}
  environment:
    STAGE: ${sls:stage}

custom:
  myStage: ${sls:stage, self:provider.stage}
  esbuild:
    sourcemap: false

functions:
  saveUser:
    name: ${self:service}-${sls:stage}-saveUser
    handler: src/users/lambdas/saveUser.handler
    timeout: 30
    events:
      - http:
          method: POST
          path: /users
          private: true
  getUser:
    name: ${self:service}-${sls:stage}-getUser
    handler: src/users/lambdas/getUser.handler
    timeout: 30
    events:
      - http:
          method: GET
          path: /users/{id}
          private: true
