name: createUserStepFunction-${sls:stage}
definition:
  Comment: 'A Step Function to create a user.'
  StartAt: GetUserData
  States:
    GetUserData:
      Type: Task
      Resource:
        Fn::GetAtt: [get-user-data, Arn]
    Next: ShouldCreateUser
    ShouldCreateUser:
      Type: Choice
      Choices:
        - Variables: '$.isExisted'
          BooleanEquals: true
          Next: CreateUser
      Default: UserCreationSkipped
    UserCreationSkipped:
      Type: Fail
      Cause: 'User already exists'
    CreateUser:
      Type: Task
      Resource:
        Fn::GetAtt: [create-user, Arn]
      Next: UserCreatedSuccess
    UserCreatedSuccess:
      Type: Success
