name: createUserStepFunction-${sls:stage}
definition:
  Comment: 'A Step Function to create a user.'
  StartAt: GetUserData
  States:
    GetUserData:
      Type: Task
      Resource:
        Fn::GetAtt: [sampleLambda, Arn]
      End: true
