name: createUserStepFunction-${sls:stage}
events:
  - http:
      method: POST
      path: /users/create
      private: true
definition:
  Comment: 'A Step Function to create a user.'
  StartAt: GetUserData
  States:
    GetUserData:
      Type: Task
      Resource:
        Fn::GetAtt: [getUserData, Arn]
      End: true
