name: createUserStepFunction-${sls:stage}
definition:
  Comment: 'A Step Function to create a user.'
  StartAt: GetUserData
  States:
    GetUserData:
      Type: Task
      Resource:
        Fn::GetAtt: [get-user-data, Arn]
    Next: ShouldCreateUser
    ShouldCreateUser:
      Type: Choice
      Choices:
        - Variables: '$.isExisted'
          BooleanEquals: true
          Next: UserCreationSkipped
      Default: CreateUser
    UserCreationSkipped:
      Type: Success
    CreateUser:
      Type: Task
      Resource:
        Fn::GetAtt: [create-user, Arn]
      Next: UserCreatedSuccess
    UserCreatedSuccess:
      Type: Success
